### ISSUE TITLE
add time zone support

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#11]
To implement Django's [Time Zone support](https://docs.djangoproject.com/en/dev/topics/i18n/timezones/), I think JSON `Date` objects will have to be stored in MongoDB instead of strings. This will make [implementing date lookups](https://github.com/mongodb-labs/django-mongodb/issues/9) easier, however, a disadvantage of JSON `Date` objects is that the finest resolution they support is millisecond, not microsecond.

**Comment by ShaneHarvey** [comment]
I propose we store dates as BSON dates even though this type only support milliseconds. From the Django docs:
> When support for time zones is enabled, Django stores datetime information in UTC in the database, uses time-zone-aware datetime objects internally, and translates them to the end user’s time zone in templates and forms.

This is the same as a pymongo/MongoDB app; we use and return time-zone-aware datetime objects to the user but only send UTC to the database.
