### ISSUE TITLE
add support for GenericForeignKey and GenericRelation

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#121]
Supporting Django's [`GenericForeignKey` and `GenericRelation`](https://docs.djangoproject.com/en/stable/ref/contrib/contenttypes/#generic-relations) requires defining two other fields on the model: `object_id` and `content_type`:

```python
class TaggedItem(models.Model):
    tag = models.SlugField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
```
For MongoDB, however, `object_id` must store an `ObjectId` corresponding to the related object's primary key rather than an integer corresponding to a numeric primary key.

Thus far, I have changed instance of `object_id = models.PositiveIntegerField()` in Django's test suite to `object_id = models.CharField(max_length=24)` and haven't encountered any problems. While triaging `aggregation_regress.tests.AggregationTests.test_aggregation_with_generic_reverse_relation` (currently listed in expected failures), however, @WaVEV suggested `object_id` may need to be defined using a new `ObjectIdField` for it to work.

That said, the admin's `LogEntry` model uses [`object_id = models.TextField(_("object id"), blank=True, null=True)`](https://github.com/django/django/blob/f5ddd54986172c29c32f5d835584ea237d5a3781/django/contrib/admin/models.py#L122), so if there are limitations with this approach, we should be aware.

Django test app: `generic_relations`

**Comment by WaVEV** [comment]
I was looking at this field to use ObjectId as a primary key. Implementing it wouldn’t be very complex, but it’s not easy for me to decide what behavior it should have. Let’s consider the following scenarios:

1.  In MongoDB, the `_id` field can be an integer, string, ObjectId, or even embedded documents.
2.  Assuming embedded documents aren’t provided, are we going to support user-defined numbers or strings?
3.  How much would performance be impacted if we had to run queries using case statements or `$convert` ($toString) operations?
