### ISSUE TITLE
Forking django-mongodb for DocumentDB Compatibility

### ISSUE THREAD

**Issue by iYasha** [mongodb-labs/django-mongodb#174]
Hi there! First, I just want to say that you're doing an amazing job with this library—thanks for all the hard work!

I'm reaching out because I'm using [AWS DocumentDB](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html), which only supports around [34% of the MongoDB API](https://www.mongodb.com/docs/drivers/documentdb-support/). Unfortunately, DocumentDB has limited support for $expr, which makes it challenging to use the library in its current state since recent updates rely on $expr queries.

I understand that $expr migration was an important step for your roadmap, and I definitely don’t want to slow down your progress by asking for special accommodations for DocumentDB. Instead, I'll be forking the repository to adjust it for DocumentDB compatibility.

Would you be comfortable with this approach, or do you have any concerns or advice for me? I’ll keep an eye on your updates and align my fork with future improvements whenever possible. Thanks again for all your efforts!

**Comment by iYasha** [comment]
Thanks for the quick response!

To make it compatible with DocumentDB, we would need to roll back the changes from [this merge request (#54)](https://github.com/mongodb-labs/django-mongodb/pull/54), which moved toward $expr-based queries. I agree that rolling back this MR isn't the best idea given the library's MongoDB-focused goals.

With that in mind, would you be okay with me maintaining a fork specifically for DocumentDB compatibility? This would allow me to adjust for DocumentDB's API limitations without impacting the primary project’s development.

Thanks again for your support and guidance!

**Comment by aclark4life** [comment]
> Would you be comfortable with me maintaining this fork specifically for DocumentDB compatibility?

As long as you comply with the [terms of the license](https://github.com/mongodb-labs/django-mongodb?tab=Apache-2.0-1-ov-file#readme) that sounds fine. Good luck!

**Comment by iYasha** [comment]
Thanks!
