### ISSUE TITLE
PYTHON-4675: add support for QuerySet.union()

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#72]
The signature is: `QuerySet.union(*other_qs, all=False)`.

It looks like MongoDB's [`$unionWith` aggregation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unionWith/) is equivalent to `UNION ALL` so our backend may have to raise `NotSupportedError` unless `QuerySet.union(..., all=True)`.

The tests are in `queries/test_qs_combinators.py`.

**Comment by Jibola** [comment]
We could solve this with a two-phase operation. 
if we notice `QuerySet.union(..., all=True)` we will use `$UnionWith`. If it is not set, we can add an additional stage to use `$group` with [`$addToSet`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/addToSet/#mongodb-group-grp.-addToSet) which will give us a set of unique documents that match the UNION operation.

**Comment by WaVEV** [comment]
@Jibola I think we don't need to do an add to set, we can just do a [group](https://www.mongodb.com/docs/manual/reference/operator/aggregation/group/#retrieve-distinct-values)
