### ISSUE TITLE
Count() in QuerySet.annotate() crashes: Unknown expression $count

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#79]
QuerySet: `Author.objects.annotate(c=Count("id"))`

SQL:
```
SELECT "annotations_author"."id",
       "annotations_author"."name",
       "annotations_author"."age",
       COUNT("annotations_author"."id") AS "c"
FROM "annotations_author"
GROUP BY "annotations_author"."id",
         "annotations_author"."name",
         "annotations_author"."age"
```
MQL:
`{'$project': {'_id': 1, 'name': 1, 'age': 1, 'c': {'$count': ['$_id']}}}`
Error:
`pymongo.errors.OperationFailure: Invalid $project :: caused by :: Unknown expression $count,`

If the query can't be expressed correctly, django-mongodb should raise a helpful NotSupportedError, and the limitation should be documented in the README.

**Comment by WaVEV** [comment]
Maybe fixing #12  will fix this one too.

**Comment by timgraham** [comment]
Fixed by https://github.com/mongodb-labs/django-mongodb/pull/84: add support for QuerySet.aggregate().
